-- This file was generated by CloneTrooper1019's Roblox Studio Mod Manager.
-- It provides external information to custom CoreScripts that are trying to fork code based on the current branch they are on.
-- If you bypass the readonly flag and start editing this file, it may not be updated correctly.
local ScriptContext = game:GetService("ScriptContext")

local GetModManagerBranch = Instance.new("BindableFunction")
GetModManagerBranch.Name = "GetModManagerBranch"
GetModManagerBranch.Archivable = false
GetModManagerBranch.Parent = ScriptContext

function GetModManagerBranch.OnInvoke()
	return %MOD_MANAGER_VERSION%
end